/**
 * PF-734 — Authorization Code + PKCE, in a real browser, in a real SPA.
 * MVP gate item 2 / PRD p.5 Testing Scenario 2.
 *
 * ── What makes this different from L04's test ───────────────────────────────
 * L04 (PF-102) proves the SERVER does PKCE correctly, and it does that against
 * a fixture. TS-2's wording is *"from a registered web app"*, and a fixture page
 * is not one — it ships to nobody, it has no bundle, and it cannot be wrong in
 * the way a real client is wrong. This drives `dist/` — the same static files a
 * developer would deploy — served cross-origin from Ship, with the verifier
 * generated by Web Crypto inside the page.
 *
 * ── The assertion that carries the ticket ──────────────────────────────────
 * *"`code_verifier` appears ONLY in the `/oauth/token` request body, never in a
 * URL, query string, or `Referer`."*
 *
 * That is asserted against every request the browser made, from the network
 * layer, rather than by reading the source. Source-reading proves what the
 * author intended; the network log proves what the browser did — and the gap
 * between those two is where this class of leak lives (a redirect that carries
 * a fragment, a `Referer` on a third-party asset, an analytics beacon).
 *
 * ── No `setTimeout` anywhere (p.11) ────────────────────────────────────────
 * Every wait is a Playwright expectation on observable state.
 */
import { test, expect, type Page, type Request } from '@playwright/test';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = join(HERE, '..', 'dist');

const SHIP_BASE_URL = `http://localhost:${process.env.DEMO_API_PORT ?? 3124}`;
const DEMO_USER = { email: 'dev@ship.local', password: 'admin123' };

/**
 * Every request the page made, with everything a verifier could hide in.
 *
 * `postData` is captured as a string rather than parsed: the assertion is
 * "does this byte sequence appear anywhere it should not", and parsing would
 * decide in advance which fields to look at.
 */
interface Recorded {
  url: string;
  method: string;
  postData: string | null;
  referer: string | undefined;
}

function recordRequests(page: Page): Recorded[] {
  const log: Recorded[] = [];
  page.on('request', (request: Request) => {
    log.push({
      url: request.url(),
      method: request.method(),
      postData: request.postData(),
      referer: request.headers()['referer'],
    });
  });
  return log;
}

/**
 * Signs the browser into Ship so `/oauth/authorize` renders consent instead of
 * bouncing to `/login`.
 *
 * `page.request` shares the browser context's cookie jar, so the `session_id`
 * cookie this sets is the one the consent screen will see. This is the human
 * being already signed in — which is the normal state when a third-party app
 * sends someone to an authorization endpoint.
 */
async function signIntoShip(page: Page): Promise<void> {
  // Ship's INTERNAL surface is CSRF-protected with a synchroniser token, so the
  // login POST needs one. This is Ship's own web login, not part of the OAuth
  // flow — the demo never touches it, and never sees this cookie.
  const csrf = await page.request.get(`${SHIP_BASE_URL}/api/csrf-token`);
  const { token } = (await csrf.json()) as { token: string };

  const response = await page.request.post(`${SHIP_BASE_URL}/api/auth/login`, {
    headers: { 'x-csrf-token': token },
    data: DEMO_USER,
  });
  expect(
    response.ok(),
    `Could not sign ${DEMO_USER.email} into Ship (${response.status()}). Run: pnpm db:seed`,
  ).toBe(true);
}

/** Drives the whole flow: sign in → consent → Allow → back on the demo. */
async function completeAuthorization(page: Page): Promise<void> {
  await page.goto('/');
  await expect(page.getByTestId('screen-logged-out')).toBeVisible();

  await signIntoShip(page);
  await page.getByTestId('sign-in').click();

  // Ship's own consent screen, on Ship's origin.
  await expect(page).toHaveURL(new RegExp(`^${SHIP_BASE_URL}/oauth/authorize`));
  await page.getByRole('button', { name: 'Allow' }).click();
}

test.describe('PF-734 · Authorization Code + PKCE from a registered web app', () => {
  test('completes the round trip and renders the signed-in user documents', async ({ page }) => {
    await completeAuthorization(page);

    await expect(page.getByTestId('screen-logged-in')).toBeVisible();
    await expect(page.getByTestId('documents').getByTestId('document').first()).toBeVisible();

    // The rendered list is the proof the token WORKS, not merely that one was
    // issued: these rows came back from `GET /api/v1/documents` with the bearer
    // token the exchange produced.
    const rendered = await page.getByTestId('document').count();
    expect(
      rendered,
      'The demo should render documents from /api/v1/documents. Run: pnpm db:seed',
    ).toBeGreaterThan(0);

    await expect(page.getByTestId('scopes')).toHaveText('documents:read');
  });

  test('the code_verifier appears ONLY in the token request body', async ({ page }) => {
    const requests = recordRequests(page);
    await completeAuthorization(page);
    await expect(page.getByTestId('screen-logged-in')).toBeVisible();

    // Recover the verifier the page actually generated. Reading it out of the
    // page rather than fixing it in the test is what makes the assertion about
    // THIS run: a hard-coded value could pass while the demo transmitted a
    // different string entirely.
    const tokenRequest = requests.find(
      (r) => r.method === 'POST' && r.url === `${SHIP_BASE_URL}/oauth/token`,
    );
    expect(tokenRequest, 'the demo never POSTed to /oauth/token').toBeDefined();

    const body = new URLSearchParams(tokenRequest?.postData ?? '');
    const verifier = body.get('code_verifier');
    expect(verifier, 'the token request carried no code_verifier').toBeTruthy();
    expect(verifier).toHaveLength(43);

    const needle = verifier as string;

    for (const request of requests) {
      // (a) never in a URL — which covers the query string and the fragment,
      //     and therefore browser history, server access logs and the address
      //     bar.
      expect(request.url, `code_verifier leaked into a URL: ${request.url}`).not.toContain(needle);

      // (b) never in a Referer. This is the leak that survives (a): a URL that
      //     never held the verifier cannot leak it here, so this assertion is
      //     really a guard against a future edit that puts it in one.
      expect(
        request.referer ?? '',
        `code_verifier leaked into a Referer header on ${request.url}`,
      ).not.toContain(needle);

      // (c) in a body, only the token request's.
      if (request.postData?.includes(needle)) {
        expect(request.url).toBe(`${SHIP_BASE_URL}/oauth/token`);
        expect(request.method).toBe('POST');
      }
    }

    // And the positive half — the authorization leg carried the CHALLENGE, so
    // the flow really was PKCE and not a bare authorization code with the
    // assertions above passing vacuously.
    const authorize = requests.find((r) => r.url.startsWith(`${SHIP_BASE_URL}/oauth/authorize?`));
    expect(authorize, 'the demo never reached /oauth/authorize').toBeDefined();
    const params = new URL(authorize?.url ?? '').searchParams;
    expect(params.get('code_challenge_method')).toBe('S256');
    expect(params.get('code_challenge')).toHaveLength(43);
    expect(params.get('code_challenge')).not.toBe(needle);
  });

  test('the token exchange sends no client_secret, and none is in the built assets', async ({
    page,
  }) => {
    const requests = recordRequests(page);
    await completeAuthorization(page);
    await expect(page.getByTestId('screen-logged-in')).toBeVisible();

    const tokenRequest = requests.find(
      (r) => r.method === 'POST' && r.url === `${SHIP_BASE_URL}/oauth/token`,
    );
    const body = new URLSearchParams(tokenRequest?.postData ?? '');
    expect(body.get('client_secret')).toBeNull();
    expect(body.get('client_id')).toBe('ship_demo_browser_pkce');

    // The static-asset half of the same claim. A demo that omits the secret on
    // the wire but ships it in a bundle has published it just as thoroughly —
    // `view-source` is the whole attack.
    //
    // ── The literal grep the ticket asks for is WRONG, and this is why ──────
    // PF-734 says "a grep over the built assets finds no `client_secret`". Run
    // literally, that fails — and it fails for a reason that is not a leak.
    // `@ship/sdk`'s `exchangeRefreshToken` contains
    //
    //     params.set('client_secret', deps.clientSecret)
    //
    // guarded by `clientSecret !== undefined`, and the browser bundle carries
    // that code because the refresh path is part of the runtime-neutral core.
    // The string in the bundle is a PARAMETER NAME with no value bound to it.
    //
    // Reporting that as a leak would be a false positive; deleting the
    // assertion would be worse. So the check is tightened rather than dropped:
    // every occurrence must be a bare `.set("client_secret"` call — a form
    // field name — and any occurrence that binds a literal (`client_secret=…`,
    // `"client_secret":"…"`) fails. That is what "no secret in the bundle"
    // actually means, and it catches the thing the loose grep was aiming at.
    // See L99 F71.
    const assets = join(DIST, 'assets');
    const files = readdirSync(assets).filter((name) => name.endsWith('.js'));
    expect(files.length, 'no built JS found — did `vite build` run?').toBeGreaterThan(0);

    for (const file of files) {
      const source = readFileSync(join(assets, file), 'utf8');
      for (const match of source.matchAll(/client_secret/g)) {
        const before = source.slice(Math.max(0, match.index - 6), match.index);
        expect(
          before,
          `client_secret in ${file} is not a bare parameter name — check for an inlined secret`,
        ).toMatch(/\.set\(["']$/);
      }
      // And the direct form: nothing anywhere assigns it a value.
      expect(source, `an inlined client_secret value in ${file}`).not.toMatch(
        /client_secret["']?\s*[:=]\s*["'][^"']/,
      );
    }
    expect(readFileSync(join(DIST, 'index.html'), 'utf8')).not.toContain('client_secret');
  });

  test('the demo source itself cannot send a client_secret', async () => {
    // The other half, and the one that keeps the bundle assertion honest: the
    // demo has no code path that could produce one, minified or not. A grep
    // over OUR sources has no false positive to tolerate, so it is exact.
    const src = join(HERE, '..', 'src');
    for (const name of readdirSync(src)) {
      const source = readFileSync(join(src, name), 'utf8');
      // Comments explain WHY there is no secret, which is not the same as
      // having one — strip line comments and block comments before looking.
      const code = source
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/^\s*\/\/.*$/gm, '');
      expect(code, `${name} references client_secret`).not.toContain('client_secret');
    }
  });
});

test.describe('PF-735 · the mandatory negative case is UI state, not a swallowed rejection', () => {
  test('a wrong code_verifier renders an error, writes no tokens, and stays retryable', async ({
    page,
  }) => {
    await page.goto('/');
    await expect(page.getByTestId('screen-logged-out')).toBeVisible();

    await signIntoShip(page);

    // Corrupt the verifier AFTER the challenge has been sent, so the challenge
    // Ship recorded and the verifier the demo presents no longer agree. This is
    // p.5's case exactly: *"a wrong code_verifier on the token exchange returns
    // invalid_grant"*, driven through the real client rather than with `curl`.
    //
    // Done by rewriting sessionStorage between the two legs, which is the only
    // way to break exactly this one thing: patching `fetch` would test the
    // patch, and registering a second app would test a different app.
    await page.getByTestId('sign-in').click();
    await expect(page).toHaveURL(new RegExp(`^${SHIP_BASE_URL}/oauth/authorize`));

    let exchangeStatus: number | null = null;
    page.on('response', (response) => {
      if (response.url() === `${SHIP_BASE_URL}/oauth/token`) exchangeStatus = response.status();
    });

    // The demo's own origin owns that storage, so the tamper has to happen
    // there — after Allow redirects back, but before the page reads it. An
    // `init` script runs before any page script on every navigation, which is
    // the deterministic hook for that; no timing, no sleep.
    await page.addInitScript(() => {
      const KEY = 'ship.demo.pkce.verifier';
      const original = sessionStorage.getItem(KEY);
      if (original) sessionStorage.setItem(KEY, 'W'.repeat(43));
    });

    await page.getByRole('button', { name: 'Allow' }).click();

    // 1. a visible error, in the page, in words.
    const error = page.getByTestId('error');
    await expect(error).toBeVisible();
    await expect(error).toContainText(/invalid_grant/i);

    // 2. RFC 6749 §5.2's code, from the server, on the wire.
    expect(exchangeStatus, 'the exchange should have been rejected').toBe(400);

    // 3. nothing persisted. This is the half that matters most: a demo that
    //    shows an error and still wrote a partial credential leaves the user
    //    stuck in a state no retry clears.
    const stored = await page.evaluate(() => window.localStorage.getItem('ship.sdk.credentials'));
    expect(stored, 'a failed exchange must write nothing to localStorage').toBeNull();

    // 4. logged out, and able to try again.
    await expect(page.getByTestId('screen-logged-out')).toBeVisible();
    await expect(page.getByTestId('sign-in')).toBeEnabled();
  });
});

test.describe('PF-736 · the browser ITokenStore finally has a consumer', () => {
  test('a corrupted credential reads as logged out, with no write-back', async ({ page }) => {
    await completeAuthorization(page);
    await expect(page.getByTestId('screen-logged-in')).toBeVisible();

    const GARBAGE = 'this is not json';
    await page.evaluate((value) => {
      window.localStorage.setItem('ship.sdk.credentials', value);
    }, GARBAGE);

    // Recording starts HERE, after the authorization that set the credential up,
    // so every request it holds is one the corrupt read provoked.
    const afterCorruption = recordRequests(page);

    await page.reload();

    // Logged out, and NOT a retry loop — `sdk/src/auth/tokenStore.ts` states
    // that contract in a comment and nothing in the repo exercised it until now
    // (p.12 requires the corrupted-token-store failure mode to be documented).
    await expect(page.getByTestId('screen-logged-out')).toBeVisible();

    // "performs no retry loop" was PROSE until 2026-08-15: nothing in this file
    // counted a request, so a demo that bounced straight back into
    // `/oauth/authorize` on every corrupt read — the exact failure the phrase
    // names — passed all three assertions around it. A retry loop is visible as
    // a re-entry into the authorization endpoint, so that is what is counted.
    // Zero, not "few": the contract is that a corrupt credential leaves the user
    // logged out and waiting, and re-authorizing is something the human asks for
    // by clicking sign-in.
    const reauthorizations = afterCorruption.filter((r) =>
      r.url.startsWith(`${SHIP_BASE_URL}/oauth/authorize`),
    );
    expect(
      reauthorizations.map((r) => r.url),
      'a corrupt credential sent the demo back to /oauth/authorize — that is the retry loop PF-736 forbids',
    ).toEqual([]);

    // The store must NOT have overwritten the value. `clear()` is a write, the
    // contract forbids writing back on a corrupt read, and a value the SDK
    // cannot parse may still be one a human can repair.
    const after = await page.evaluate(() =>
      window.localStorage.getItem('ship.sdk.credentials'),
    );
    expect(after).toBe(GARBAGE);
  });

  test('a session survives a reload through localStorage', async ({ page }) => {
    await completeAuthorization(page);
    await expect(page.getByTestId('screen-logged-in')).toBeVisible();

    await page.reload();

    // No second trip through /oauth/authorize: the anti-vacuity half of the
    // test above. A store that read as logged-out ALWAYS would pass the
    // corruption case and be useless.
    await expect(page.getByTestId('screen-logged-in')).toBeVisible();
    await expect(page.getByTestId('document').first()).toBeVisible();
  });
});
