# ShipShape local configuration — hashicorp/local
#
# Renders every environment file the app reads from one declarative source, so
# that "what is in my .env" becomes a reviewable diff instead of a shell
# heredoc. Before this, `scripts/dev.sh:36` wrote `api/.env.local` with `cat >`
# and a literal `SESSION_SECRET=dev-secret-change-in-production`, and the web
# and API files had no common source at all.
#
# Four managed local resources (p.8 asks for at least two):
#
#   local_sensitive_file.api_env         api/.env.local        0600
#   local_file.web_env                   web/.env.local        0644
#   local_file.app_config                app.config.json       0644
#   local_file.deploy_manifest           deploy-manifest.json  0644
#
# Plus one random_password, which is why `random` is also pinned here.
#
# This root is deliberately standalone: no backend block, no remote state, no
# credentials. It runs offline on a clean machine with `terraform init &&
# terraform apply`, which is the property the existing AWS roots do not have —
# they cannot even `init` without the aws CLI and an SSM lookup to discover the
# backend bucket name.

locals {
  # Normalised once so every rendered file agrees. A drift in these values
  # between the API env, the web env, and the manifest was previously possible
  # because three different scripts wrote them.
  api_base_url = var.environment == "local" ? "http://localhost:${var.api_port}" : "https://api-${var.environment}.ship.internal"
  web_base_url = var.environment == "local" ? "http://localhost:${var.web_port}" : "https://${var.environment}.ship.internal"
  ws_base_url  = replace(local.api_base_url, "http", "ws")

  node_env = var.environment == "prod" ? "production" : "development"

  # Generated, not chosen: if the caller supplies a secret we use it, otherwise
  # the random_password below. Coalesce keeps the sensitivity marking.
  session_secret = coalesce(var.session_secret, random_password.session_secret.result)

  # Every generated file carries this. It is the single most useful thing to put
  # at the top of a generated file: it tells the next engineer not to hand-edit,
  # and names the command that regenerates it.
  banner = "Generated by terraform/local-config — do not edit by hand. Run 'terraform apply' in that directory to regenerate."
}

# Dev/shadow session secret. Not used for prod: prod should pass
# -var session_secret=... from a secrets manager, because a value generated here
# lives only in this state file and regenerating it logs every user out.
resource "random_password" "session_secret" {
  length  = 48
  special = false # base62 keeps it safe to paste into a .env file unquoted

  keepers = {
    # Rotate deliberately by bumping environment, never incidentally.
    environment = var.environment
  }
}

# ── Resource 1 ────────────────────────────────────────────────────────────────
# The API environment file. Sensitive variant: content is redacted from plan
# output, and the file lands 0600 rather than the provider default 0777.
resource "local_sensitive_file" "api_env" {
  filename        = "${var.output_dir}/api/.env.local"
  file_permission = "0600"
  # local_file defaults directory_permission to 0777. Setting it explicitly
  # matters when output_dir does not exist yet and the provider creates it.
  directory_permission = "0750"

  content = <<-EOT
    # ${local.banner}
    # environment=${var.environment}
    DATABASE_URL=${var.database_url}
    SESSION_SECRET=${local.session_secret}
    PORT=${var.api_port}
    NODE_ENV=${local.node_env}
    ENVIRONMENT=${var.environment}
    CORS_ORIGIN=${local.web_base_url}
    APP_BASE_URL=${local.web_base_url}
  EOT
}

# ── Resource 2 ────────────────────────────────────────────────────────────────
# The web build environment file. Vite only exposes VITE_-prefixed vars to the
# browser bundle, so nothing secret belongs here — hence local_file, not
# local_sensitive_file. Getting that distinction wrong is how a secret ends up
# in a public JS bundle.
resource "local_file" "web_env" {
  filename             = "${var.output_dir}/web/.env.local"
  file_permission      = "0644"
  directory_permission = "0750"

  content = <<-EOT
    # ${local.banner}
    VITE_API_URL=${local.api_base_url}
    VITE_WS_URL=${local.ws_base_url}
    VITE_APP_ENV=${var.environment}
  EOT
}

# ── Resource 3 ────────────────────────────────────────────────────────────────
# Runtime configuration. jsonencode rather than a heredoc so the file is always
# valid JSON and the plan diff is structural — Terraform renders a jsonencode
# diff key by key, which is what makes the drift demo readable.
resource "local_file" "app_config" {
  filename             = "${var.output_dir}/app.config.json"
  file_permission      = "0644"
  directory_permission = "0750"

  content = jsonencode({
    service     = "shipshape-api"
    environment = var.environment
    port        = var.api_port
    logging = {
      level  = var.log_level
      format = var.environment == "local" ? "pretty" : "json"
    }
    # Timeout and retry knobs kept next to the code that needs them rather than
    # hardcoded at each call site.
    http = {
      requestTimeoutMs = 30000
      shutdownGraceMs  = 10000
      keepAliveTimeout = 65000
    }
    database = {
      poolMax          = var.environment == "prod" ? 20 : 5
      connectTimeoutMs = 5000
      statementTimeout = 30000
    }
    session = {
      idleTimeoutMinutes     = 15
      absoluteTimeoutMinutes = 720
    }
  })
}

# ── Resource 4 ────────────────────────────────────────────────────────────────
# Artifact provenance (implementation rule 5). Records which commit and which
# exact provider versions produced this set of files, so a rendered environment
# can be traced back to a checkout.
resource "local_file" "deploy_manifest" {
  filename             = "${var.output_dir}/deploy-manifest.json"
  file_permission      = "0644"
  directory_permission = "0750"

  content = jsonencode({
    service     = "shipshape"
    environment = var.environment
    gitSha      = var.git_sha
    providers = {
      "hashicorp/local"  = "2.9.0"
      "hashicorp/random" = "3.9.0"
    }
    renders = [
      "api/.env.local",
      "web/.env.local",
      "app.config.json",
    ]
  })
}
