/**
 * PF-020 — capture the Part 1 performance baseline.
 *
 *     pnpm --filter @ship/api exec tsx src/scripts/measure-baseline.ts
 *     pnpm baseline:measure                                    (from the repo root)
 *
 * Writes `docs/baseline-part1.json`. That file is the denominator for the +10%
 * regression budget on the MVP gate (PRD p.2 item 9, targets on p.6): after
 * PlugForge lands, L26's `compare-baseline.ts` re-measures and compares. It fails
 * loudly if the baseline is missing or empty, so this must produce real numbers —
 * a stubbed file would turn the one measured gate item into a rubber stamp.
 *
 * Three measurements, because the budget names three things:
 *
 *   P95 latency          per route, in-process through the Express app
 *   bundle size          web/dist JS + CSS, raw and gzipped
 *   per-route queries    how many SQL statements one request issues
 *
 * The measurement itself — the route list, the sample counts, the percentile rule,
 * the fixture, the query counting and the bundle glob — lives in
 * `lib/perf-measure.ts` and is shared verbatim with the comparator, so the two
 * sides of the +10% comparison cannot drift apart (PF-802).
 *
 * The output schema is documented in `docs/baseline-schema.md`.
 */
import { writeFileSync } from 'node:fs';
import {
  BASELINE_PATH,
  type Baseline,
  currentGitSha,
  describeMethod,
  measureBundle,
  measureRoutes,
  summarize,
} from './lib/perf-measure.js';
import { pool } from '../db/client.js';

async function main(): Promise<void> {
  process.env.NODE_ENV = process.env.NODE_ENV ?? 'test';

  const routes = await measureRoutes((id, m) => {
    console.log(
      `  ${id.padEnd(26)} p95 ${String(m.latencyMs.p95).padStart(7)} ms   ` +
        `${String(m.queriesPerRequest).padStart(2)} quer${m.queriesPerRequest === 1 ? 'y' : 'ies'}`,
    );
  });

  const bundle = measureBundle();

  const baseline: Baseline = {
    $schema: 'https://ship.internal/schemas/baseline-part1.json',
    _comment:
      'GENERATED by api/src/scripts/measure-baseline.ts (PF-020). The denominator for the +10% ' +
      'regression budget on MVP gate item 9 (PRD p.2, targets p.6). Do not hand-edit — re-run the script.',
    capturedAt: new Date().toISOString(),
    gitRef: process.env.GIT_SHA ?? currentGitSha(),
    method: await describeMethod(),
    budget: {
      maxRegressionPercent: 10,
      appliesTo: ['latencyMs.p95 per route', 'bundle.totalGzipBytes', 'queriesPerRequest per route'],
      source: 'PRD p.2 (MVP gate item 9), p.6 (Performance Targets)',
    },
    summary: summarize(routes, bundle),
    routes,
    bundle,
  };

  writeFileSync(BASELINE_PATH, JSON.stringify(baseline, null, 2) + '\n');

  console.log(`\n  bundle  ${bundle.totalBytes} B raw / ${bundle.totalGzipBytes} B gzip across ${bundle.fileCount} files`);
  console.log(`  wrote   ${BASELINE_PATH}`);

  await pool.end();

  // Explicit exit. `createApp()` starts things that outlive the measurement —
  // the CAIA initialiser's timers among them — so the event loop stays alive
  // after the last request and the process hangs with the file already written.
  // A script CI runs must terminate; hanging at 100% success looks identical to
  // hanging at a failure.
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
